# Generated by Django 6.0.6 on 2026-06-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('special', 'Special')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_trips', to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop_requests', to='transport.stop')),
                ('requested_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_stop_requests', to='transport.stop')),
                ('service_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_change_requests', to='trip.servicetrip')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_change_requests', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TravelConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('auto_confirmed', 'Auto Confirmed')], max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_confirmations', to='trip.servicetrip')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_confirmations', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='TripBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_assignments', to='transport.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_assignments', to='accounts.driver')),
                ('service_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_assignments', to='trip.servicetrip')),
            ],
        ),
    ]
