# Generated by Django 6.0.6 on 2026-06-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transport', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('cancelled', 'Cancelled')], max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.student')),
                ('trip_bus_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trip.tripbusassignment')),
            ],
        ),
    ]
